### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by jvl4422** [cisc-322/cisc-322.github.io#2]
Designing the landing page :DD

It must include the title, as well as a brief overview of the project. It should also include space for our group name once we decide what it is.

**Comment by jvl4422** [comment]
@anishkabarran randomly got this colour scheme, thoughts? https://coolors.co/b9d6f2-061a40-0353a4-006daa-003559

**Comment by anishkabarran** [comment]
@jvl4422 not bad! definitely will narrow it down to less colours, id say B9D6F2, 006DAA, and 003559 with an off white and almost dark black like F1F1F1 and 1B1B1B
